### ISSUE TITLE
ENRs appear out of order

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNodePackage-obol#6]
**Describe the bug**

Order of the ENR clusters in the config tab seems to be at random.

<img width="437" alt="Screenshot 2024-01-31 at 15 41 09" src="https://github.com/dappnode/DAppNodePackage-obol/assets/19168735/d556b02f-cdd5-4556-af2d-c6814f5af5aa">

**To Reproduce**

<!--Steps to reproduce the behavior:
Visit config tab of Obol Package

**Expected behavior**

Ordered ascending.

**Comment by dappnodedev** [comment]
Already fixed in Dappmanager
